import { StyleSheet } from "react-native";

export const AppStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F8FAFC" },
  container: { paddingHorizontal: 16 },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 14,
    shadowColor: "#0F172A",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  h1: { fontSize: 24, fontWeight: "800", color: "#0F172A" },
  h2: { fontSize: 18, fontWeight: "800", color: "#0F172A" },
  p: { fontSize: 14, color: "#475569" },
  label: { fontSize: 13, fontWeight: "700", color: "#334155" },
  headerCard: {
    backgroundColor: "#0B5ED7",
    borderRadius: 18,
    padding: 16,
    overflow: "hidden",
  },
  headerTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "900" },
  headerSubtitle: { color: "#DBEAFE", marginTop: 4 },
  input: {
    marginTop: 6,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: "#0F172A",
  },
  btnPrimary: {
    height: 44,
    borderRadius: 12,
    backgroundColor: "#0B5ED7",
    alignItems: "center",
    justifyContent: "center",
  },
  btnPrimaryText: { color: "#FFFFFF", fontWeight: "800" },
  btnOutline: {
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  btnOutlineText: { color: "#0F172A", fontWeight: "800" },
  btnDangerOutline: {
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#FDA4AF",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  btnDangerOutlineText: { color: "#BE123C", fontWeight: "800" },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
  },
  badgeText: { fontSize: 12, fontWeight: "800" },
});
